/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthedSponsorsRouteImport } from './routes/_authed/sponsors'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedScheduleRouteImport } from './routes/_authed/schedule'
import { Route as AuthedRolesRouteImport } from './routes/_authed/roles'
import { Route as AuthedPostsRouteImport } from './routes/_authed/posts'
import { Route as AuthedOpiRouteImport } from './routes/_authed/opi'
import { Route as AuthedMembersRouteImport } from './routes/_authed/members'
import { Route as AuthedFinanceRouteImport } from './routes/_authed/finance'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedCalendarRouteImport } from './routes/_authed/calendar'
import { Route as AuthedBuildHoursRouteImport } from './routes/_authed/build-hours'
import { Route as AuthedPostsIndexRouteImport } from './routes/_authed/posts.index'
import { Route as AuthedPostsPostIdRouteImport } from './routes/_authed/posts.$postId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSponsorsRoute = AuthedSponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedScheduleRoute = AuthedScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRolesRoute = AuthedRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPostsRoute = AuthedPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOpiRoute = AuthedOpiRouteImport.update({
  id: '/opi',
  path: '/opi',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMembersRoute = AuthedMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedFinanceRoute = AuthedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCalendarRoute = AuthedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBuildHoursRoute = AuthedBuildHoursRouteImport.update({
  id: '/build-hours',
  path: '/build-hours',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPostsIndexRoute = AuthedPostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedPostsRoute,
} as any)
const AuthedPostsPostIdRoute = AuthedPostsPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => AuthedPostsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/build-hours': typeof AuthedBuildHoursRoute
  '/calendar': typeof AuthedCalendarRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/finance': typeof AuthedFinanceRoute
  '/members': typeof AuthedMembersRoute
  '/opi': typeof AuthedOpiRoute
  '/posts': typeof AuthedPostsRouteWithChildren
  '/roles': typeof AuthedRolesRoute
  '/schedule': typeof AuthedScheduleRoute
  '/settings': typeof AuthedSettingsRoute
  '/sponsors': typeof AuthedSponsorsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/posts/$postId': typeof AuthedPostsPostIdRoute
  '/posts/': typeof AuthedPostsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/build-hours': typeof AuthedBuildHoursRoute
  '/calendar': typeof AuthedCalendarRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/finance': typeof AuthedFinanceRoute
  '/members': typeof AuthedMembersRoute
  '/opi': typeof AuthedOpiRoute
  '/roles': typeof AuthedRolesRoute
  '/schedule': typeof AuthedScheduleRoute
  '/settings': typeof AuthedSettingsRoute
  '/sponsors': typeof AuthedSponsorsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/posts/$postId': typeof AuthedPostsPostIdRoute
  '/posts': typeof AuthedPostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/_authed/build-hours': typeof AuthedBuildHoursRoute
  '/_authed/calendar': typeof AuthedCalendarRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/finance': typeof AuthedFinanceRoute
  '/_authed/members': typeof AuthedMembersRoute
  '/_authed/opi': typeof AuthedOpiRoute
  '/_authed/posts': typeof AuthedPostsRouteWithChildren
  '/_authed/roles': typeof AuthedRolesRoute
  '/_authed/schedule': typeof AuthedScheduleRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/sponsors': typeof AuthedSponsorsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authed/posts/$postId': typeof AuthedPostsPostIdRoute
  '/_authed/posts/': typeof AuthedPostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/logout'
    | '/signup'
    | '/build-hours'
    | '/calendar'
    | '/dashboard'
    | '/finance'
    | '/members'
    | '/opi'
    | '/posts'
    | '/roles'
    | '/schedule'
    | '/settings'
    | '/sponsors'
    | '/auth/callback'
    | '/posts/$postId'
    | '/posts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/logout'
    | '/signup'
    | '/build-hours'
    | '/calendar'
    | '/dashboard'
    | '/finance'
    | '/members'
    | '/opi'
    | '/roles'
    | '/schedule'
    | '/settings'
    | '/sponsors'
    | '/auth/callback'
    | '/posts/$postId'
    | '/posts'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/logout'
    | '/signup'
    | '/_authed/build-hours'
    | '/_authed/calendar'
    | '/_authed/dashboard'
    | '/_authed/finance'
    | '/_authed/members'
    | '/_authed/opi'
    | '/_authed/posts'
    | '/_authed/roles'
    | '/_authed/schedule'
    | '/_authed/settings'
    | '/_authed/sponsors'
    | '/auth/callback'
    | '/_authed/posts/$postId'
    | '/_authed/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  SignupRoute: typeof SignupRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/sponsors': {
      id: '/_authed/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof AuthedSponsorsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/schedule': {
      id: '/_authed/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AuthedScheduleRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/roles': {
      id: '/_authed/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AuthedRolesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/posts': {
      id: '/_authed/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof AuthedPostsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/opi': {
      id: '/_authed/opi'
      path: '/opi'
      fullPath: '/opi'
      preLoaderRoute: typeof AuthedOpiRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/members': {
      id: '/_authed/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AuthedMembersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/finance': {
      id: '/_authed/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthedFinanceRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/calendar': {
      id: '/_authed/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthedCalendarRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/build-hours': {
      id: '/_authed/build-hours'
      path: '/build-hours'
      fullPath: '/build-hours'
      preLoaderRoute: typeof AuthedBuildHoursRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/posts/': {
      id: '/_authed/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof AuthedPostsIndexRouteImport
      parentRoute: typeof AuthedPostsRoute
    }
    '/_authed/posts/$postId': {
      id: '/_authed/posts/$postId'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof AuthedPostsPostIdRouteImport
      parentRoute: typeof AuthedPostsRoute
    }
  }
}

interface AuthedPostsRouteChildren {
  AuthedPostsPostIdRoute: typeof AuthedPostsPostIdRoute
  AuthedPostsIndexRoute: typeof AuthedPostsIndexRoute
}

const AuthedPostsRouteChildren: AuthedPostsRouteChildren = {
  AuthedPostsPostIdRoute: AuthedPostsPostIdRoute,
  AuthedPostsIndexRoute: AuthedPostsIndexRoute,
}

const AuthedPostsRouteWithChildren = AuthedPostsRoute._addFileChildren(
  AuthedPostsRouteChildren,
)

interface AuthedRouteChildren {
  AuthedBuildHoursRoute: typeof AuthedBuildHoursRoute
  AuthedCalendarRoute: typeof AuthedCalendarRoute
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedFinanceRoute: typeof AuthedFinanceRoute
  AuthedMembersRoute: typeof AuthedMembersRoute
  AuthedOpiRoute: typeof AuthedOpiRoute
  AuthedPostsRoute: typeof AuthedPostsRouteWithChildren
  AuthedRolesRoute: typeof AuthedRolesRoute
  AuthedScheduleRoute: typeof AuthedScheduleRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedSponsorsRoute: typeof AuthedSponsorsRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedBuildHoursRoute: AuthedBuildHoursRoute,
  AuthedCalendarRoute: AuthedCalendarRoute,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedFinanceRoute: AuthedFinanceRoute,
  AuthedMembersRoute: AuthedMembersRoute,
  AuthedOpiRoute: AuthedOpiRoute,
  AuthedPostsRoute: AuthedPostsRouteWithChildren,
  AuthedRolesRoute: AuthedRolesRoute,
  AuthedScheduleRoute: AuthedScheduleRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedSponsorsRoute: AuthedSponsorsRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  SignupRoute: SignupRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
